name: 'Python Action'

on:
  schedule:
    - cron: '20 0,6 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  jobs_1:
    name: 'Match etf rsi'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Python 3.x'
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - name: 'Install dependencies'
      run: |
        echo 'run at:' `date '+%Y-%m-%d %H:%M:%S'`
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'Run script'
      env:
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
      run: |
        echo 'run at:' `date '+%Y-%m-%d %H:%M:%S'`
        python etf/rsi_match.py
