name: 'Python Action'

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '20 6 * * 1,2,3,4,5'
    - cron: '5 7 * * 1,2,3,4,5'

env:
  TZ: Asia/Shanghai

jobs:
  jobs_1:
    name: 'Match Rules'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Python 3.x'
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - name: 'Install chinese font'
      run: |
        sudo apt-get install ttf-wqy-microhei
        fc-list :lang=zh-cn
    - name: 'Install dependencies'
      run: |
        echo 'run at:' `date '+%Y-%m-%d %H:%M:%S'`
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'Run script'
      env:
        GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
      run: |
        echo 'run at:' `date '+%Y-%m-%d %H:%M:%S'`
        python main.py
    - name: 'Commit and push if changed'
      run: |
        git diff
        git config --global user.email "jelly_54@163.com"
        git config --global user.name "zhangguodong"
        git pull
        git add -A
        git commit -m "🎨Update statistics" || exit 0
        git push